# Generated by Django 5.2 on 2025-04-29 16:12

import file_storage.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to=file_storage.models.user_directory_path),
        ),
    ]
