# Generated by Django 5.2 on 2025-05-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='data_type',
            new_name='object_type',
        ),
    ]
