# Generated by Django 5.2 on 2025-05-17 21:35

import file_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_alter_userfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=file_storage.models.user_directory_path),
        ),
    ]
