# Generated by Django 5.2 on 2025-05-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_alter_userfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='path',
            field=models.CharField(db_index=True, default=None, max_length=500),
            preserve_default=False,
        ),
    ]
