# Generated by Django 5.2 on 2025-04-30 19:37

import file_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0004_alter_userfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file',
            field=models.FileField(upload_to=file_storage.models.user_directory_path),
        ),
    ]
