# Generated by Django 5.2 on 2025-05-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0005_userfile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='path',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
